/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ink3d.UserInterface.Import;

import ink3d.UserInterface.MainMenu.BadFieldException;
import ink3d.UserInterface.MainMenu.MainWindow;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tim
 */
public class ImportPanel extends javax.swing.JPanel {
    private ImportController importController;
    /**
     * Creates new form ImportPanel
     */
    public ImportPanel() {
        this.importController = new ImportController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImportPanel = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        StlList = new javax.swing.JList();
        jPanel53 = new javax.swing.JPanel();
        jLabel205 = new javax.swing.JLabel();
        importImportButton = new javax.swing.JButton();
        deleteImportButton = new javax.swing.JButton();

        StlList.setModel(new javax.swing.AbstractListModel() {
            private ImportController  controller = new ImportController();
            public int getSize() { return controller.getStlFiles().size(); }
            public Object getElementAt(int i) { return controller.getStlFiles().get(i); }
        });
        StlList.setToolTipText("");
        jScrollPane11.setViewportView(StlList);

        jPanel53.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel205.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel205.setText("STL Models");

        importImportButton.setText("Import");
        importImportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                importImportButtonMouseReleased(evt);
            }
        });

        deleteImportButton.setText("Delete");
        deleteImportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteImportButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ImportPanelLayout = new javax.swing.GroupLayout(ImportPanel);
        ImportPanel.setLayout(ImportPanelLayout);
        ImportPanelLayout.setHorizontalGroup(
            ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
            .addGroup(ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ImportPanelLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ImportPanelLayout.createSequentialGroup()
                            .addGap(207, 207, 207)
                            .addComponent(importImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(deleteImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ImportPanelLayout.createSequentialGroup()
                                .addComponent(jLabel205)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ImportPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jPanel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGap(16, 16, 16)))
        );
        ImportPanelLayout.setVerticalGroup(
            ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
            .addGroup(ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ImportPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(importImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteImportButton))
                    .addGap(1, 1, 1)
                    .addComponent(jLabel205)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addComponent(jPanel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(20, 20, 20)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ImportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ImportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void importImportButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importImportButtonMouseReleased
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            if(!importController.importStl(file.getPath())){
                JOptionPane.showMessageDialog(null, "File Read Error", "InfoBox: " + "Unable to read file", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            MainWindow.printJobPanel.updateSubsectionPanels();
            this.StlList.setModel(new javax.swing.AbstractListModel() {
                private final ImportController  controller = new ImportController();
                @Override
                public int getSize() { return controller.getStlFiles().size(); }
                @Override
                public Object getElementAt(int i) { return controller.getStlFiles().get(i); }
            }
        );

        }
    }//GEN-LAST:event_importImportButtonMouseReleased

    private void deleteImportButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteImportButtonMouseReleased
        String fileName = (String)this.StlList.getSelectedValue();
        try {
            if(!importController.deleteStl(fileName)){
                JOptionPane.showMessageDialog(null,"InfoBox: " + "Unable to delete file: "+fileName, "File Delete Error" , JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        } catch (BadFieldException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"InfoBox: " + "No Selection" , JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        MainWindow.printJobPanel.updateSubsectionPanels();
        this.StlList.setModel(new javax.swing.AbstractListModel() {
            private final ImportController  controller = new ImportController();
            @Override
            public int getSize() { return controller.getStlFiles().size(); }
            @Override
            public Object getElementAt(int i) { return controller.getStlFiles().get(i); }
        }
        );
    }//GEN-LAST:event_deleteImportButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ImportPanel;
    private javax.swing.JList StlList;
    private javax.swing.JButton deleteImportButton;
    private javax.swing.JButton importImportButton;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JScrollPane jScrollPane11;
    // End of variables declaration//GEN-END:variables
}
