/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ink3d.UserInterface.PrinterConfig;

import ink3d.UserInterface.MainMenu.BadFieldException;
import ink3d.UserInterface.MainMenu.MainWindow;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tim
 */
public class PrinterPanel extends javax.swing.JPanel {
    private static ArrayList<String> extruderListArrayListForPrinter = new ArrayList<>();
    private PrinterController printerController;
    /**
     * Creates new form PrinterPanel
     */
    public PrinterPanel() {
        this.printerController = new PrinterController();
        initComponents();
    }
    public javax.swing.JComboBox getExtruderCombo(){
        return this.extruderSelectionPrinterComboBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        newPrinterButton = new javax.swing.JButton();
        savePrinterButton = new javax.swing.JButton();
        loadPrinterButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bedXPrinterText = new javax.swing.JTextField();
        bedYPrinterText = new javax.swing.JTextField();
        zOffsetPrinterText = new javax.swing.JTextField();
        printCenterXPrinterText = new javax.swing.JTextField();
        printCenterYPrinterText = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        vibrationPrinterText = new javax.swing.JTextField();
        numExtrudersPrinterText = new javax.swing.JTextField();
        numExtrudersPrinterText.setText("0");
        relativeEDistancePrinterCombo = new javax.swing.JComboBox();
        gCodeFlavorPrinterCombo = new javax.swing.JComboBox();
        jLabel206 = new javax.swing.JLabel();
        firmwareRetractionPrinterCombo = new javax.swing.JComboBox();
        jScrollPane18 = new javax.swing.JScrollPane();
        extruderListPrinter = new javax.swing.JList();
        addExtruderToPrinterButton = new javax.swing.JButton();
        addExtruderToPrinterButton1 = new javax.swing.JButton();
        extruderSelectionPrinterComboBox = new javax.swing.JComboBox();
        jPanel19 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        startGCodePrinterTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        endGCodePrinterTextArea = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        printerListPrinter = new javax.swing.JList();
        namePrinterText = new javax.swing.JTextField();
        deletePriinterButton = new javax.swing.JButton();

        newPrinterButton.setText("New");
        newPrinterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newPrinterButtonMouseReleased(evt);
            }
        });

        savePrinterButton.setText("Save");
        savePrinterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                savePrinterButtonMouseReleased(evt);
            }
        });

        loadPrinterButton.setText("Load");
        loadPrinterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loadPrinterButtonMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Name:");

        jScrollPane3.setBackground(new java.awt.Color(102, 102, 102));

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setFocusTraversalPolicyProvider(true);
        jPanel15.setPreferredSize(new java.awt.Dimension(300, 602));

        jPanel16.setPreferredSize(new java.awt.Dimension(300, 119));
        jPanel16.setVerifyInputWhenFocusTarget(false);

        jLabel7.setText("Bed X:");

        jLabel8.setText("Bed Y:");

        jLabel11.setText("Print Center X:");

        jLabel12.setText("Print Center Y:");

        jLabel13.setText("Z Offset:");

        bedXPrinterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedXPrinterTextActionPerformed(evt);
            }
        });

        bedYPrinterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedYPrinterTextActionPerformed(evt);
            }
        });

        zOffsetPrinterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zOffsetPrinterTextActionPerformed(evt);
            }
        });

        printCenterXPrinterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printCenterXPrinterTextActionPerformed(evt);
            }
        });

        printCenterYPrinterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printCenterYPrinterTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(bedXPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bedYPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printCenterXPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printCenterYPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(zOffsetPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(bedXPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printCenterXPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(bedYPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printCenterYPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(zOffsetPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel14.setText("G Code Flavor:");

        jLabel15.setText("Relative E Distance:");

        jLabel16.setText("Number of Extruders:");

        jLabel17.setText("Vibration Limit");

        vibrationPrinterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrationPrinterTextActionPerformed(evt);
            }
        });

        numExtrudersPrinterText.setEnabled(false);
        numExtrudersPrinterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numExtrudersPrinterTextActionPerformed(evt);
            }
        });

        relativeEDistancePrinterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        gCodeFlavorPrinterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "reprap", "teacup", "makerbot", "sailfish", "mach3", "no-extrusion" }));

        jLabel206.setText("Firmware Restraction:");

        firmwareRetractionPrinterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        extruderListPrinter.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() { return PrinterPanel.extruderListArrayListForPrinter.size(); }
            @Override
            public Object getElementAt(int i) { return PrinterPanel.extruderListArrayListForPrinter.get(i); }
        });
        extruderListPrinter.setToolTipText("");
        jScrollPane18.setViewportView(extruderListPrinter);

        addExtruderToPrinterButton.setText("Add Extruder");
        addExtruderToPrinterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addExtruderToPrinterButtonMouseReleased(evt);
            }
        });

        addExtruderToPrinterButton1.setText("Remove Extruder");
        addExtruderToPrinterButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addExtruderToPrinterButton1MouseReleased(evt);
            }
        });

        extruderSelectionPrinterComboBox.setModel(new DefaultComboBoxModel(this.printerController.loadExtruderList().toArray()));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relativeEDistancePrinterCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gCodeFlavorPrinterCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vibrationPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numExtrudersPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel206, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firmwareRetractionPrinterCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addExtruderToPrinterButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(addExtruderToPrinterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extruderSelectionPrinterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(gCodeFlavorPrinterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extruderSelectionPrinterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(relativeEDistancePrinterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addExtruderToPrinterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(numExtrudersPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addExtruderToPrinterButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(vibrationPrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel206)
                    .addComponent(firmwareRetractionPrinterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel25.setText("Custom Gcode:");

        jLabel26.setText("Start G Code:");

        jLabel27.setText("End G Code:");

        startGCodePrinterTextArea.setColumns(20);
        startGCodePrinterTextArea.setRows(5);
        jScrollPane4.setViewportView(startGCodePrinterTextArea);

        endGCodePrinterTextArea.setColumns(20);
        endGCodePrinterTextArea.setRows(5);
        jScrollPane5.setViewportView(endGCodePrinterTextArea);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addComponent(jScrollPane5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel15);

        printerListPrinter.setModel(new javax.swing.AbstractListModel() {
            private PrinterController  controller = new PrinterController();
            public int getSize() { return controller.getPrinterConfigurations().size(); }
            public Object getElementAt(int i) { return controller.getPrinterConfigurations().get(i); }
        });
        printerListPrinter.setToolTipText("");
        jScrollPane12.setViewportView(printerListPrinter);

        deletePriinterButton.setText("Delete");
        deletePriinterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePriinterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namePrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(newPrinterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(savePrinterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loadPrinterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deletePriinterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPrinterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePrinterButton)
                    .addComponent(loadPrinterButton)
                    .addComponent(deletePriinterButton))
                .addGap(9, 9, 9)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namePrinterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newPrinterButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPrinterButtonMouseReleased
        this.namePrinterText.setText(null);
        this.bedXPrinterText.setText(null);
        this.bedYPrinterText.setText(null);
        this.printCenterXPrinterText.setText(null);
        this.printCenterYPrinterText.setText(null);
        this.zOffsetPrinterText.setText(null);
        this.gCodeFlavorPrinterCombo.setSelectedIndex(0);
        this.relativeEDistancePrinterCombo.setSelectedIndex(0);
        this.numExtrudersPrinterText.setText("0");
        this.vibrationPrinterText.setText(null);
        this.firmwareRetractionPrinterCombo.setSelectedItem(0);
        this.startGCodePrinterTextArea.setText(null);
        this.endGCodePrinterTextArea.setText(null);
        PrinterPanel.extruderListArrayListForPrinter = new ArrayList<>();
        this.extruderListPrinter.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() { return PrinterPanel.extruderListArrayListForPrinter.size(); }
            @Override
            public Object getElementAt(int i) { return PrinterPanel.extruderListArrayListForPrinter.get(i); }
        });
    }//GEN-LAST:event_newPrinterButtonMouseReleased

    private void savePrinterButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePrinterButtonMouseReleased
        ArrayList<String> varList = new ArrayList<>();
        varList.add(this.namePrinterText.getText());
        varList.add(this.bedXPrinterText.getText());
        varList.add(this.bedYPrinterText.getText());
        varList.add(this.printCenterXPrinterText.getText());
        varList.add(this.printCenterYPrinterText.getText());
        varList.add(this.zOffsetPrinterText.getText());
        varList.add(this.gCodeFlavorPrinterCombo.getSelectedItem().toString());
        varList.add(this.relativeEDistancePrinterCombo.getSelectedItem().toString());
        varList.add(this.numExtrudersPrinterText.getText());
        varList.add(this.vibrationPrinterText.getText());
        varList.add(this.firmwareRetractionPrinterCombo.getSelectedItem().toString());
        varList.add(this.startGCodePrinterTextArea.getText());
        varList.add(this.endGCodePrinterTextArea.getText());
        ArrayList<String> extruderList = new ArrayList<>();
        for (String extruderName : PrinterPanel.extruderListArrayListForPrinter){
            extruderList.add(extruderName);
        }
        try{
            printerController.savePrinterConfiguratoin(varList, extruderList);
            this.printerListPrinter.setModel(new javax.swing.AbstractListModel() {
                private final PrinterController  controller = new PrinterController();
                @Override
                public int getSize() { return controller.getPrinterConfigurations().size(); }
                @Override
                public Object getElementAt(int i) { return controller.getPrinterConfigurations().get(i); }
            }
        );
        }catch(BadFieldException e){
            JOptionPane.showMessageDialog(null, e.getMessage() , "InfoBox: " + "Bad Field Data",JOptionPane.INFORMATION_MESSAGE);
        }
        MainWindow.printJobPanel.getPrinterComboBox().setModel(new DefaultComboBoxModel(printerController.getPrinterConfigurations().toArray()));
        MainWindow.printJobPanel.updateUI();
    }//GEN-LAST:event_savePrinterButtonMouseReleased

    private void loadPrinterButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadPrinterButtonMouseReleased
        ArrayList<String> varList = new ArrayList<>();
        try {
            varList = printerController.loadPrinterConfiguration((String) this.printerListPrinter.getSelectedValue());
        } catch (BadFieldException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"InfoBox: " + "No Selection" , JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        this.namePrinterText.setText(varList.get(0));
        this.bedXPrinterText.setText(varList.get(1));
        this.bedYPrinterText.setText(varList.get(2));
        this.printCenterXPrinterText.setText(varList.get(3));
        this.printCenterYPrinterText.setText(varList.get(4));
        this.zOffsetPrinterText.setText(varList.get(5));
        this.gCodeFlavorPrinterCombo.setSelectedItem(varList.get(6));
        this.relativeEDistancePrinterCombo.setSelectedItem(varList.get(7));
        this.numExtrudersPrinterText.setText(varList.get(8));
        this.vibrationPrinterText.setText(varList.get(9));
        this.firmwareRetractionPrinterCombo.setSelectedItem(varList.get(10));
        this.startGCodePrinterTextArea.setText(varList.get(11));
        this.endGCodePrinterTextArea.setText(varList.get(12));
        PrinterPanel.extruderListArrayListForPrinter = printerController.loadMyExtruders(varList.get(0));
        this.extruderListPrinter.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() { return PrinterPanel.extruderListArrayListForPrinter.size(); }
            @Override
            public Object getElementAt(int i) { return PrinterPanel.extruderListArrayListForPrinter.get(i); }
        });
    }//GEN-LAST:event_loadPrinterButtonMouseReleased

    private void bedXPrinterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedXPrinterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bedXPrinterTextActionPerformed

    private void bedYPrinterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedYPrinterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bedYPrinterTextActionPerformed

    private void zOffsetPrinterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zOffsetPrinterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zOffsetPrinterTextActionPerformed

    private void printCenterXPrinterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printCenterXPrinterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printCenterXPrinterTextActionPerformed

    private void printCenterYPrinterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printCenterYPrinterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printCenterYPrinterTextActionPerformed

    private void vibrationPrinterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrationPrinterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vibrationPrinterTextActionPerformed

    private void numExtrudersPrinterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numExtrudersPrinterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numExtrudersPrinterTextActionPerformed

    private void addExtruderToPrinterButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExtruderToPrinterButtonMouseReleased
        PrinterPanel.extruderListArrayListForPrinter.add(this.extruderSelectionPrinterComboBox.getSelectedItem().toString());
        int currentNumExtruders;
        currentNumExtruders = 1 + Integer.parseInt(this.numExtrudersPrinterText.getText());
        this.numExtrudersPrinterText.setText(Integer.toString(currentNumExtruders));
        this.extruderListPrinter.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() { return PrinterPanel.extruderListArrayListForPrinter.size(); }
            @Override
            public Object getElementAt(int i) { return PrinterPanel.extruderListArrayListForPrinter.get(i); }
        });
    }//GEN-LAST:event_addExtruderToPrinterButtonMouseReleased

    private void addExtruderToPrinterButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExtruderToPrinterButton1MouseReleased
        if(this.extruderListPrinter.getSelectedIndex() == -1)return;
        PrinterPanel.extruderListArrayListForPrinter.remove(this.extruderListPrinter.getSelectedIndex());
        int currentNumExtruders;
        currentNumExtruders = Integer.parseInt(this.numExtrudersPrinterText.getText()) - 1;
        this.numExtrudersPrinterText.setText(Integer.toString(currentNumExtruders));
        this.extruderListPrinter.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() { return PrinterPanel.extruderListArrayListForPrinter.size(); }
            @Override
            public Object getElementAt(int i) { return PrinterPanel.extruderListArrayListForPrinter.get(i); }
        });
    }//GEN-LAST:event_addExtruderToPrinterButton1MouseReleased

    private void deletePriinterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePriinterButtonActionPerformed
        String fileName = (String)this.printerListPrinter.getSelectedValue();
        try {
            if(!printerController.deletePrinterConfiguration(fileName)){
                JOptionPane.showMessageDialog(null,"InfoBox: " + "Unable to delete file: " +fileName, "File Delete Error" , JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        } catch (BadFieldException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"InfoBox: " + "No Selection" , JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        this.printerListPrinter.setModel(new javax.swing.AbstractListModel() {
            private final PrinterController  controller = new PrinterController();
            @Override
            public int getSize() { return controller.getPrinterConfigurations().size(); }
            @Override
            public Object getElementAt(int i) { return controller.getPrinterConfigurations().get(i); }
        }
        );
    }//GEN-LAST:event_deletePriinterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExtruderToPrinterButton;
    private javax.swing.JButton addExtruderToPrinterButton1;
    private javax.swing.JTextField bedXPrinterText;
    private javax.swing.JTextField bedYPrinterText;
    private javax.swing.JButton deletePriinterButton;
    private javax.swing.JTextArea endGCodePrinterTextArea;
    private javax.swing.JList extruderListPrinter;
    private javax.swing.JComboBox extruderSelectionPrinterComboBox;
    private javax.swing.JComboBox firmwareRetractionPrinterCombo;
    private javax.swing.JComboBox gCodeFlavorPrinterCombo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton loadPrinterButton;
    private javax.swing.JTextField namePrinterText;
    private javax.swing.JButton newPrinterButton;
    private javax.swing.JTextField numExtrudersPrinterText;
    private javax.swing.JTextField printCenterXPrinterText;
    private javax.swing.JTextField printCenterYPrinterText;
    private javax.swing.JList printerListPrinter;
    private javax.swing.JComboBox relativeEDistancePrinterCombo;
    private javax.swing.JButton savePrinterButton;
    private javax.swing.JTextArea startGCodePrinterTextArea;
    private javax.swing.JTextField vibrationPrinterText;
    private javax.swing.JTextField zOffsetPrinterText;
    // End of variables declaration//GEN-END:variables
}
