G21
G28
G90
M104
G1 Z5 F200
G1 X10 Y10 F600
M109
G1 E10

T0
; generated by Slic3r 1.0.0 on 2014-04-25 at 15:33:02

; layer_height = 0.2
; perimeters = 2
; top_solid_layers = 1
; bottom_solid_layers = 1
; fill_density = 0.5
; perimeter_speed = 10.0
; infill_speed = 10.0
; travel_speed = 130.0
; nozzle_diameter = 0.35
; filament_diameter = 1.75
; extrusion_multiplier = 1.0
; perimeters extrusion width = 0.35mm
; infill extrusion width = 0.52mm
; solid infill extrusion width = 0.52mm
; top infill extrusion width = 0.52mm
; first layer extrusion width = 0.35mm

G21 ; set units to millimeters
M107
M104 S190 ; set temperature

M109 S190 ; wait for temperature to be reached
G90 ; use absolute coordinates
G92 E0
M82 ; use absolute distances for extrusion
M104 S0
G28 X0 Y0
M84

